### ISSUE TITLE
Feature request: Dark mode for Mojave

### ISSUE THREAD

**Issue by keirwilliams-old** [vitorgalvao/fog#11]
Might not be an easy endeavour, but could be done with some custom styles. Could be an imitation of the iOS app's dark colour scheme.

**Comment by vitorgalvao** [comment]
> Might not be an easy endeavour, but could be done with some custom styles.

It’s a boring lengthy task, more than anything, especially since we’re overwriting someone else’s CSS styles and I like to keep these changes with as few overrides as possible.

To put it bluntly, I appreciate the feature request but I question the usefulness of the work considering the time sink it would be with no reward. I don’t have any concrete numbers on how many people use Fog, but considering the low number of stars and issues/PRs and that I never got a single donation for it, I doubt a considerable number of people would care enough. I mean, *I would use the dark mode*, but right now I don’t want it bad enough to justify the investment.

I’d even be wary to say I’d accept a PR, because I’m not sure I would. Take as an example [some recent styling improvements that were submitted](https://github.com/vitorgalvao/fog/pull/8/files) and [what I eventually ended up doing](https://github.com/vitorgalvao/fog/pull/9/files). It was basically a rewrite.

Again, thank you for the interest and the feature request. I do plan to keep working on Fog, but I’m closing the issue as this is unlikely to get done (soon?).
