### ISSUE TITLE
Support playthrough

### ISSUE THREAD

**Issue by Amorymeltzer** [vitorgalvao/fog#2]
Right now, upon finishing listening to something, nothing happens.  At a bare minimum, returning home would be appropriate, but it would be great to support playing through the "next" item.  This would allow the support of playlists, which would be fantastic.

**Comment by vitorgalvao** [comment]
> returning home would be appropriate

I’m not entirely sure it would, since by returning home you just lost the episode, and hence the option to permalink/share link. Not sure that’s something that would trip anyone, though, so I see no trouble in doing it for now (it’s done in the latest release, that I am releasing now).

As for playing the next item, I’m not sure we can do so. Overcast’s website doesn’t have playlists or a concept of a next item, so how could we tap into that? How would we pick what the next item is? Overcast’s website groups podcasts in an arguably weird way and there are even extensions to order them in a different manner, but that I feel would be imposing a preference, and even if we could pick a new order there’s nothing to say it’s the order in which you want to play podcasts _right now_.

All of that could be “fixed” by a settings page, but I’d like to avoid that.

At the end of the day, Fog is simply a web wrapper that needs to suffers from (most of) the same limitations as the official website. Though I was able to make multiple additions and even a few behaviour modifications, I’d like to avoid very complex additions since even the simplest ones are hacks on top of the website. For those, I’d more readily consider a pull request than working on them directly.

I am, however, envisioning a system where we could simply drag and drop the episodes in order on the homepage (giving us effectively a single playlist) and I do like that system, but put it bluntly, I don’t trust Marco to not break that (as is his right, but I also do not want to be wasting my time, since it’s something that can be broken on a whim). Conversely, I also think he doesn’t care at all about the website, so that might actually be a good thing to consider this in the future and I’m not ruling it out.

**Comment by vitorgalvao** [comment]
Just noticed this didn’t work very well (see commit message from https://github.com/vitorgalvao/fog/commit/742640aec1285d38b02422fb11a4ee180e26408b).

Just [released an update](https://github.com/vitorgalvao/fog/releases/tag/v1.1.0) with the fix and a bunch other niceties.
